// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsT-309A6oHHRG8ZumtDt4q8EeC4ZgoBc',
    appId: '1:552031247451:web:0e11b4564f3c630100737e',
    messagingSenderId: '552031247451',
    projectId: 'oreganoai-e7f49',
    authDomain: 'oreganoai-e7f49.firebaseapp.com',
    storageBucket: 'oreganoai-e7f49.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQKMzBDwYCle1ekAGjJHBMc92usX6Yu2A',
    appId: '1:552031247451:android:a42e99ed7c3210cc00737e',
    messagingSenderId: '552031247451',
    projectId: 'oreganoai-e7f49',
    storageBucket: 'oreganoai-e7f49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWINeV5hA4k5BjEOjmA84xreiuT5ldVSU',
    appId: '1:552031247451:ios:306b8abb7e15d6fe00737e',
    messagingSenderId: '552031247451',
    projectId: 'oreganoai-e7f49',
    storageBucket: 'oreganoai-e7f49.firebasestorage.app',
    iosBundleId: 'com.example.organoai',
  );
}
